[package]
name = "stamp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rcgen = "0.11"
x509-parser = "0.15"
tokio = { version = "1.35", features = ["full"] }

[workspace]
members = []
